//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Makhmutov4438ParfumeriaApp.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class parfumerDbEntitiess : DbContext
    {
        public parfumerDbEntitiess()
            : base("name=parfumerDbEntitiess")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Заказы> Заказы { get; set; }
        public virtual DbSet<ПВЗ> ПВЗ { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Продукты> Продукты { get; set; }
        public virtual DbSet<ТоварыПродукты> ТоварыПродукты { get; set; }
    }
}
