//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Makhmutov4438ParfumeriaApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заказы()
        {
            this.ТоварыПродукты = new HashSet<ТоварыПродукты>();
        }
    
        public int НомерЗаказа { get; set; }
        public System.DateTime ДатаЗаказа { get; set; }
        public System.DateTime ДатаВыдачи { get; set; }
        public int IdПВЗ { get; set; }
        public string Имя { get; set; }
        public string Фамилия { get; set; }
        public string Отчество { get; set; }
        public int Код { get; set; }
        public Nullable<int> IdПользователь { get; set; }
        public string Статус { get; set; }
    
        public virtual ПВЗ ПВЗ { get; set; }
        public virtual Пользователи Пользователи { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ТоварыПродукты> ТоварыПродукты { get; set; }
    }
}
