//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Makhmutov4438ParfumeriaApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продукты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Продукты()
        {
            this.ТоварыПродукты = new HashSet<ТоварыПродукты>();
        }
    
        public int Id { get; set; }
        public string Артикул { get; set; }
        public string Наименование { get; set; }
        public string ЕдиницаИзмерения { get; set; }
        public int Стоимость { get; set; }
        public int МаксСкидка { get; set; }
        public string Производитель { get; set; }
        public string Поставщик { get; set; }
        public string Категория { get; set; }
        public int ДейстСкидка { get; set; }
        public int Количество { get; set; }
        public string Описание { get; set; }
        public byte[] Изображение { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ТоварыПродукты> ТоварыПродукты { get; set; }
    }
}
